name: ChestProtection
version: 1.0.7
main: pl.amazingshit.cp.ChestProtection
description: Protects your containers.
author: DaAmazingShit
commands:
    cp:
        usage: /<command>
        aliases: [chestprotection, container, chest, furnace, dispenser, jukebox]
        description: Container protection manager
    reloadcp:
        usage: /reloadcp
        aliases: [cpr, rcp]
        description: Reloads ChestProtection configurations