name: ChestProtection
version: 1.2
main: pl.amazingshit.cp.ChestProtection
description: Protects your containers.
author: DaAmazingShit
commands:
    cp:
        usage: /<command>
        aliases: [chestprotection, container, chest, furnace, dispenser, jukebox]
        description: Container protection manager
    cpreload:
        usage: /cpreload
        aliases: [cpr, rcp]
        description: Reloads ChestProtection configurations